# Generated by Django 4.2.29 on 2026-04-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_international', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_brand', models.CharField(max_length=50)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('billing_address', models.TextField(blank=True)),
                ('customer_country', models.CharField(blank=True, max_length=100)),
                ('customer_postal_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'card_payments',
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
                ('received_by', models.CharField(max_length=100)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'cash_payments',
            },
            bases=('payments.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.user'),
        ),
    ]
