# Generated by Django 4.2.29 on 2026-04-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('max_users', models.IntegerField(default=1)),
                ('max_invoices', models.IntegerField(default=10)),
                ('gst_validation', models.BooleanField(default=False)),
                ('eway_bill', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('custom_branding', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'unique_together': {('name', 'billing_cycle')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='received_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('paused', 'Paused')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.user')),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('seller_gst', models.CharField(blank=True, max_length=15)),
                ('buyer_gst', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.user')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='GSTValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('is_valid', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.user')),
            ],
            options={
                'db_table': 'gst_validations',
            },
        ),
        migrations.CreateModel(
            name='EwayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway_bill_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('from_place', models.CharField(max_length=200)),
                ('from_state', models.CharField(max_length=100)),
                ('from_pincode', models.CharField(max_length=10)),
                ('to_place', models.CharField(max_length=200)),
                ('to_state', models.CharField(max_length=100)),
                ('to_pincode', models.CharField(max_length=10)),
                ('goods_description', models.TextField()),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('air', 'Air'), ('ship', 'Ship')], default='road', max_length=10)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('transporter_name', models.CharField(blank=True, max_length=200)),
                ('transporter_id', models.CharField(blank=True, max_length=50)),
                ('seller_gst', models.CharField(blank=True, max_length=15)),
                ('buyer_gst', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='generated', max_length=20)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bills', to='payments.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bills', to='payments.user')),
            ],
            options={
                'db_table': 'eway_bills',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.usersubscription'),
        ),
    ]
