# Generated by Django 4.2.29 on 2026-05-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionplan_user_gst_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ewaybill',
            old_name='transporter_id',
            new_name='consignment_note',
        ),
        migrations.RemoveField(
            model_name='gstvalidation',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='gstvalidation',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_invoices',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='abn_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Australia', 'Australia')], default='India', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revised_invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_products',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='multi_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_aud',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden')], default='draft', max_length=15),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='renewal_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('upi', 'UPI'), ('netbanking', 'Net Banking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('paused', 'Paused'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='razorpay', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('internal_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('webhook_event', models.CharField(blank=True, max_length=100)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.user')),
            ],
            options={
                'db_table': 'payment_gateway_transactions',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='payments.paymentgatewaytransaction'),
        ),
    ]
